name: chef_noodle
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# PACKAGES
dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES
  http: ^1.2.0
  intl: ^0.18.1
  logger: ^2.2.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.1.0
  
  # ICONS
  cupertino_icons: ^1.0.6

  # STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_spinkit: ^5.2.1
  chat_bubbles: ^1.5.0
  font_awesome_flutter: ^10.7.0
  iconsax: ^0.0.8
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.3
  shared_preferences: ^2.2.3
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.5
  path: ^1.9.0
  flutter_otp_text_field: ^1.2.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  flutter_launcher_icons: ^0.13.1

  # PRODUCT SPECIFIC

  # PACKAGES END

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  # LOCAL ASSETS
  assets:
    # - assets/icons/brands/
    # - assets/images/on_boarding_images/
    - assets/images/
    - assets/logos/
    - assets/logos/splash_bg.png
    - assets/icons/

  # LOCAL FONTS
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/chef_noodle_logo.png"

